---
# Domain to provision
domain_name: "staging.ttl.sh"

# Compute zone name from domain (ttl.sh)
zone_name: "ttl.sh"

# Cloudflare details
cloudflare_zone_id: "_in_doppler"
cloudflare_api_token: "_in_doppler"
cloudflare_email: "_in_doppler"
cloudflare_proxied: false

# A record target (LATITUDESH_VM_IP)
target_ip: "_in_doppler"

# Let's Encrypt contact email (using provided email)
le_email: "_in_doppler"

# Docker install settings
docker_users:
  - root

# Application deployment
app_root: /opt/ttlsh

# S3-compatible object storage backing the zot registry
s3_bucket: "_in_doppler"
s3_region: "_in_doppler"
s3_endpoint: "_in_doppler"
s3_access_key: "_in_doppler"
s3_secret_key: "_in_doppler"
s3_root_directory: "/"
