services:
  web:
    image: ghcr.io/replicatedhq/ttlsh-web:latest
    build:
      context: web
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    container_name: ttlsh-web
    restart: always
    pull_policy: always
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - ttlsh-network

  zot:
    image: ghcr.io/project-zot/zot-linux-amd64:v2.1.18
    container_name: ttlsh-zot
    restart: always
    pull_policy: always
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./zot-config.json:/etc/zot/config.json:ro
    networks:
      - ttlsh-network

networks:
  ttlsh-network:
    driver: bridge
