FROM node:10 as deps
ADD ./package.json /src/package.json
ADD ./Makefile /src/Makefile
WORKDIR /src
RUN make deps

FROM node:10
ADD . /src
WORKDIR /src
COPY --from=0 /src .
RUN make test
ENTRYPOINT ["node"]
CMD ["--no-deprecation", "build/server.js", "reap"]
