FROM node:10 as deps
COPY ./package.json /src/package.json
COPY ./Makefile /src/Makefile
COPY . /src
WORKDIR /src
RUN make deps  test

ENTRYPOINT ["node"]
CMD ["--no-deprecation", "build/server.js", "hooks"]
